### ISSUE TITLE
Value Error in line 133 (in __init__.py) since today

### ISSUE THREAD

**Issue by Danre2407** [ekeih/dwdpollen#1]
Hey,

every time I try to call your first line "api = dwdpollen.DwdPollenApi()" I get a Value Error in line 133 in the __init__.py.
Yesterday the API was working perfectly, but now I always get this Error and I haven't changed anything in the code.

Please let me know if I am the only one with this error or if is a common thing.

Thanks in advance,

Daniel

**Comment by Miraxulix** [comment]
I have the same error. It seems that Dwd does not always release their information for Sunday. This causes the DwDPollenApi to throw the Value Error.
